# Generated by Django 5.1.2 on 2024-11-04 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Vendor',
            new_name='vendor',
        ),
    ]
